// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/DmitryM7/short-url.git/internal/repository (interfaces: IStorage)

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	repository "github.com/DmitryM7/short-url.git/internal/repository"
	gomock "github.com/golang/mock/gomock"
)

// MockIStorage is a mock of IStorage interface.
type MockIStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIStorageMockRecorder
}

// MockIStorageMockRecorder is the mock recorder for MockIStorage.
type MockIStorageMockRecorder struct {
	mock *MockIStorage
}

// NewMockIStorage creates a new mock instance.
func NewMockIStorage(ctrl *gomock.Controller) *MockIStorage {
	mock := &MockIStorage{ctrl: ctrl}
	mock.recorder = &MockIStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStorage) EXPECT() *MockIStorageMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockIStorage) BatchCreate(arg0 context.Context, arg1 []repository.LinkRecord) ([]repository.LinkRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", arg0, arg1)
	ret0, _ := ret[0].([]repository.LinkRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockIStorageMockRecorder) BatchCreate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockIStorage)(nil).BatchCreate), arg0, arg1)
}

// BatchDel mocks base method.
func (m *MockIStorage) BatchDel(arg0 context.Context, arg1 int, arg2 []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BatchDel", arg0, arg1, arg2)
}

// BatchDel indicates an expected call of BatchDel.
func (mr *MockIStorageMockRecorder) BatchDel(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDel", reflect.TypeOf((*MockIStorage)(nil).BatchDel), arg0, arg1, arg2)
}

// Create mocks base method.
func (m *MockIStorage) Create(arg0 context.Context, arg1 repository.LinkRecord) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIStorageMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIStorage)(nil).Create), arg0, arg1)
}

// Get mocks base method.
func (m *MockIStorage) Get(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIStorageMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIStorage)(nil).Get), arg0, arg1)
}

// GetByURL mocks base method.
func (m *MockIStorage) GetByURL(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByURL", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByURL indicates an expected call of GetByURL.
func (mr *MockIStorageMockRecorder) GetByURL(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByURL", reflect.TypeOf((*MockIStorage)(nil).GetByURL), arg0, arg1)
}

// Ping mocks base method.
func (m *MockIStorage) Ping() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockIStorageMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockIStorage)(nil).Ping))
}

// Urls mocks base method.
func (m *MockIStorage) Urls(arg0 context.Context, arg1 int) ([]repository.LinkRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Urls", arg0, arg1)
	ret0, _ := ret[0].([]repository.LinkRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Urls indicates an expected call of Urls.
func (mr *MockIStorageMockRecorder) Urls(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Urls", reflect.TypeOf((*MockIStorage)(nil).Urls), arg0, arg1)
}
